### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-laurasanra#1]
Really cool job @laurasanra  !!!

Here you have some tips to improve the exercise:

- [x] Define a good structure of folders and files for the project
- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document
- [x] Save the random number in a variable and print it
- [x] Remember to convert input value string to a number
- [x] Execute compare function
- [x] Define the logic to make the counter work
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

You are close to the exercise solution, but here you are a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by laurasanra** [comment]
Hi @nasivuela, I think I've done all you told me. I just have one doubt: if I delete node_modules then I can't run gulp. Is there any way that I could delete it that file but still run gulp?

**Comment by nasivuela** [comment]
Good work @laurasanra !!

Forget about node_modules, I have erased that point since it was my mistake.

I'm closing this, but here you have more tips in case you want to keep improving it:
- You are writing many times `text.innerHTML = `something`;`,you can move it to a function to reuse it.
- What about adding a reset functionality
- Responsive
- ... whatever you want to try ;)

![](https://media.giphy.com/media/JltOMwYmi0VrO/giphy.gif)
